Repository jcornaz/heron, pull requests merged in 2022-02, with the labels that each got.

#190 feat: generate collision shapes from mesh via the `PendingConvexCollision` component (behind the `collision-from-mesh` feature flag)
  Cargo.toml
  README.md
  core/Cargo.toml
  core/src/collision_from_mesh.rs
  core/src/lib.rs
Labels: feature

#191 docs(readme): update example to bevy 0.6 syntax
  README.md
Labels: documentation

#193 refactor: remove all .system()
  core/src/lib.rs
  debug/src/dim2.rs
  debug/src/dim3.rs
  debug/src/lib.rs
  examples/collision_shapes_in_child_entity.rs
  examples/debug_2d.rs
  examples/demo.rs
  examples/events.rs
  examples/layers.rs
  examples/quickstart.rs
  examples/ray_casting.rs
  rapier/src/lib.rs
  rapier/src/pipeline.rs
  rapier/tests/events.rs
Labels: refactoring

#189 feat!: add normals to `CollisionData` in events
  core/Cargo.toml
  core/src/events.rs
  rapier/src/pipeline.rs
  rapier/tests/events.rs
Labels: feature, breaking
